package org.mydevnotes.mst.ui;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.networknt.schema.JsonSchema;
import com.networknt.schema.JsonSchemaFactory;
import com.networknt.schema.SpecVersion;
import com.networknt.schema.ValidationMessage;
import java.io.IOException;
import java.io.InputStream;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.config.AppConfig;

/**
 *
 * @author vupma
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanelConfig = new org.mydevnotes.mst.ui.JPanelConfig();
        jPanelSearchSection = new org.mydevnotes.mst.ui.JPanelSearchOptions();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPaneSearchResult = new javax.swing.JScrollPane();
        jPanelResultSet1 = new org.mydevnotes.mst.ui.JPanelResultSet();
        jScrollPaneDetails = new javax.swing.JScrollPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelDebugOutput = new org.mydevnotes.mst.ui.JPanelDebugOutput();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maintenance Support Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setDividerLocation(50);
        jSplitPane3.setLeftComponent(jPanelConfig);
        jSplitPane3.setRightComponent(jPanelSearchSection);

        jSplitPane1.setTopComponent(jSplitPane3);

        jSplitPane2.setDividerLocation(120);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPaneSearchResult.setViewportView(jPanelResultSet1);

        jSplitPane2.setTopComponent(jScrollPaneSearchResult);

        jSplitPane4.setDividerLocation(240);
        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        jSplitPane4.setLeftComponent(jPanel1);
        jSplitPane4.setBottomComponent(jPanelDebugOutput);

        jScrollPaneDetails.setViewportView(jSplitPane4);

        jSplitPane2.setRightComponent(jScrollPaneDetails);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        if (!ApplicationContext.getApplicationContext().configIsValid()) {
            JOptionPane.showMessageDialog(
                    JFrameMain.this,
                    "App config has errors: " + ApplicationContext.getApplicationContext().getConfigValidationErrors(),
                    "Config Error",
                    JOptionPane.ERROR_MESSAGE
            );

            System.exit(1);
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            */
           
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
           
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
       
        loadAppConfig(args);
        
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameMain jFrameMain = new JFrameMain();

                ApplicationContext.getApplicationContext().setEventLogger(jFrameMain.jPanelDebugOutput);
                jFrameMain.initConfigSection(ApplicationContext.getApplicationContext().getAppConfig());
                
                jFrameMain.initShutdownHook();

                jFrameMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private org.mydevnotes.mst.ui.JPanelConfig jPanelConfig;
    private org.mydevnotes.mst.ui.JPanelDebugOutput jPanelDebugOutput;
    private org.mydevnotes.mst.ui.JPanelResultSet jPanelResultSet1;
    private org.mydevnotes.mst.ui.JPanelSearchOptions jPanelSearchSection;
    private javax.swing.JScrollPane jScrollPaneDetails;
    private javax.swing.JScrollPane jScrollPaneSearchResult;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    // End of variables declaration//GEN-END:variables

    private static void loadAppConfig(String[] args) {
        if (args.length == 0) {
            System.out.println("Reading config json");

            ObjectMapper mapper = new ObjectMapper();
            InputStream is
                    = Thread.currentThread()
                            .getContextClassLoader()
                            .getResourceAsStream("app_config_example.json");

            JsonNode schemaNode;
            try {
                schemaNode = mapper.readTree(
                        Thread.currentThread()
                                .getContextClassLoader()
                                .getResourceAsStream("app_config_schema.json")
                );

                JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
                JsonSchema schema = factory.getSchema(schemaNode);

                JsonNode jsonNode = mapper.readTree(is);
                Set<ValidationMessage> errors = schema.validate(jsonNode);

                if (errors.isEmpty()) {
                    System.out.println("Valid JSON!");
                } else {
                    errors.forEach(System.out::println);
                    String validationErrors = errors.stream()
                            .map(ValidationMessage::getMessage)
                            .collect(Collectors.joining(System.lineSeparator()));
                    ApplicationContext.getApplicationContext().setConfigValidationErrors(validationErrors);
                    return;
                }
            } catch (IOException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                is = Thread.currentThread()
                        .getContextClassLoader()
                        .getResourceAsStream("app_config_example.json");

                AppConfig appConfig = mapper.readValue(is, AppConfig.class);

                ApplicationContext.getApplicationContext().setAppConfig(appConfig);

                appConfig.getSearchSection().getSearchOptions().forEach(search -> System.out.println("appConfig: " + search.getName()));
            } catch (IOException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void initConfigSection(AppConfig appConfig) {

        appConfig.getSources().forEach(dataSource ->  jPanelConfig.addDataSourceConfig(dataSource));
        appConfig.getSearchSection().getSearchOptions().forEach(searchOption -> jPanelSearchSection.addSearchOption(searchOption, jPanelResultSet1));

    }
    
    private void initShutdownHook() {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Closing datasources...");

            ApplicationContext.getApplicationContext().closeAllDataSources();
        }));
    }    
}
