package org.mydevnotes.mst.ui;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.networknt.schema.JsonSchema;
import com.networknt.schema.JsonSchemaFactory;
import com.networknt.schema.SpecVersion;
import com.networknt.schema.ValidationMessage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntityListener;
import org.mydevnotes.mst.EventLogger;
import org.mydevnotes.mst.config.AppConfig;

/**
 *
 * @author vupma
 */
public class JFrameMain extends javax.swing.JFrame {

    private EventLogger eventLogger;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        this.jPanelsearchResultSet.setRowHaveDetails(true);
        ApplicationContext.getApplicationContext().getApplicationController().addMainBusinessEntitySelectionListeners((BusinessEntityListener) jPanelSearchResultDetails);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanelConfigContainer = new org.mydevnotes.mst.ui.JPanelConfigContainer();
        jPanelSearchOptionsContainer = new org.mydevnotes.mst.ui.JPanelSearchOptionsContainer();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPaneDetails = new javax.swing.JScrollPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanelDebugOutput = new org.mydevnotes.mst.ui.JPanelDebugOutput();
        jPanelSearchResultDetails = new org.mydevnotes.mst.ui.JPanelSearchResultDetails();
        jPanelsearchResultSet = new org.mydevnotes.mst.ui.JPanelSearchResultSet();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maintenance Support Tool");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(80);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setDividerLocation(50);
        jSplitPane3.setLeftComponent(jPanelConfigContainer);
        jSplitPane3.setRightComponent(jPanelSearchOptionsContainer);

        jSplitPane1.setTopComponent(jSplitPane3);

        jSplitPane2.setDividerLocation(120);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane4.setDividerLocation(100);
        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane4.setBottomComponent(jPanelDebugOutput);
        jSplitPane4.setLeftComponent(jPanelSearchResultDetails);

        jScrollPaneDetails.setViewportView(jSplitPane4);

        jSplitPane2.setRightComponent(jScrollPaneDetails);
        jSplitPane2.setLeftComponent(jPanelsearchResultSet);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        if (!ApplicationContext.getApplicationContext().configIsValid()) {
            JOptionPane.showMessageDialog(
                    JFrameMain.this,
                    "App config has errors: " + ApplicationContext.getApplicationContext().getConfigValidationErrors(),
                    "Config Error",
                    JOptionPane.ERROR_MESSAGE
            );

            System.exit(1);
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            /*
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
             */
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        loadAppConfig(args);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameMain jFrameMain = new JFrameMain();

                jFrameMain.eventLogger = jFrameMain.jPanelDebugOutput;
                ApplicationContext.getApplicationContext().setEventLogger(jFrameMain.eventLogger);

                if (ApplicationContext.getApplicationContext().isConfigLoaded()) {
                    jFrameMain.initConfigSection(ApplicationContext.getApplicationContext().getAppConfig());
                }

                jFrameMain.initSearchResultSection();

                jFrameMain.initShutdownHook();

                jFrameMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.mydevnotes.mst.ui.JPanelConfigContainer jPanelConfigContainer;
    private org.mydevnotes.mst.ui.JPanelDebugOutput jPanelDebugOutput;
    private org.mydevnotes.mst.ui.JPanelSearchOptionsContainer jPanelSearchOptionsContainer;
    private org.mydevnotes.mst.ui.JPanelSearchResultDetails jPanelSearchResultDetails;
    private org.mydevnotes.mst.ui.JPanelSearchResultSet jPanelsearchResultSet;
    private javax.swing.JScrollPane jScrollPaneDetails;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    // End of variables declaration//GEN-END:variables

    private static void loadAppConfig(String[] args) {

        try {

            InputStream configFileInputStream = getConfigFileInputStream(args);

            ObjectMapper mapper = new ObjectMapper();
            JsonNode schemaNode;
            try {
                schemaNode = mapper.readTree(
                        Thread.currentThread()
                                .getContextClassLoader()
                                .getResourceAsStream("app_config_schema.json")
                );

                JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
                JsonSchema schema = factory.getSchema(schemaNode);

                JsonNode jsonNode = mapper.readTree(configFileInputStream);
                Set<ValidationMessage> errors = schema.validate(jsonNode);

                if (errors.isEmpty()) {
                    System.out.println("Valid received JSON!");
                } else {
                    errors.forEach(System.out::println);
                    String validationErrors = errors.stream()
                            .map(ValidationMessage::getMessage)
                            .collect(Collectors.joining(System.lineSeparator()));
                    ApplicationContext.getApplicationContext().setConfigValidationErrors(validationErrors);
                    return;
                }
            } catch (IOException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                configFileInputStream = getConfigFileInputStream(args);

                AppConfig appConfig = mapper.readValue(configFileInputStream, AppConfig.class);

                ApplicationContext.getApplicationContext().setAppConfig(appConfig);

                appConfig.getSearchConfig().getSearchOptions().forEach(search -> System.out.println("appConfig: " + search.getName()));
            } catch (IOException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

            ApplicationContext.getApplicationContext().setConfigPath(getConfigPath(args));

        } catch (FileNotFoundException ex) {
            System.getLogger(JFrameMain.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private static InputStream getConfigFileInputStream(String[] args) throws FileNotFoundException {
        InputStream configFileInputStream;
        if (args.length == 0) {
            System.out.println("Use default config json");

            configFileInputStream = Thread.currentThread()
                    .getContextClassLoader()
                    .getResourceAsStream("app_config_example.json");
        } else {

            System.out.println("Read config json from parameter " + args[0]);
            configFileInputStream = new FileInputStream(args[0]);

        }
        return configFileInputStream;
    }

    private static Path getConfigPath(String[] args) {

        if (args.length > 0) {
            Path configFile = Paths.get(args[0]);
            return configFile.getParent();
        }

        return null;

    }

    private void initConfigSection(AppConfig appConfig) {

        appConfig.getDataSources().forEach(dataSource -> jPanelConfigContainer.addDataSourceConfig(dataSource));
        appConfig.getSearchConfig().getSearchOptions().forEach(searchOption -> this.jPanelSearchOptionsContainer.addSearchOption(searchOption, this.jPanelsearchResultSet));

    }

    private void initShutdownHook() {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Closing datasources...");

            ApplicationContext.getApplicationContext().closeAllDataSources();
        }));
    }

    private void initSearchResultSection() {
        this.jPanelsearchResultSet.setNavigationListener(jPanelSearchResultDetails);
        ApplicationContext.getApplicationContext().getApplicationController().addSearchResultListener(jPanelsearchResultSet);
    }
}
