package org.mydevnotes.mst.ui;

import java.nio.file.Path;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntityListener;
import org.mydevnotes.mst.action.ActionScriptExecutor;
import org.mydevnotes.mst.config.Action;
import org.mydevnotes.mst.config.AppConfig;
import org.mydevnotes.mst.dao.BusinessEntity;

/**
 *
 * @author vupma
 */
public class JPanelBusinessEntityActions extends javax.swing.JPanel implements BusinessEntityListener {

    /**
     * Creates new form JPanelBusinessEntityActions
     */
    public JPanelBusinessEntityActions() {
        initComponents();
        ApplicationContext.getApplicationContext().getApplicationController().addSelectionListener((BusinessEntityListener) this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Test");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onBusinessEntitySelected(BusinessEntity businessEntity) {

        this.removeAll();

        if (businessEntity != null) {

            AppConfig appConfig = ApplicationContext.getApplicationContext().getAppConfig();

            var entityConfig = appConfig.getBusinessEntityConfig().stream().filter(cfg -> cfg.getBusinessEntityType().equals(businessEntity.getType())).findFirst().orElse(null);

            if (entityConfig != null) {

                entityConfig.getActions().forEach(actionConfig -> {
                    JButton actionButton = createActionButton(actionConfig, businessEntity);
                    this.add(actionButton);
                });
            }

            if (businessEntity.getAttributes().containsKey("export_to_timeline_enabled")) {
                Action actionConfig = new Action();
                actionConfig.setName("Show timeline");
                actionConfig.setToolTip("Open timeline in browser");
                actionConfig.setType("script");
                actionConfig.setReference("id");
                actionConfig.setScript("scripts/showTimeLine.groovy");
                actionConfig.setReferenceType("long");

                JButton actionButton = createActionButton(actionConfig, businessEntity);
                this.add(actionButton);
            }
        }

        this.revalidate();
        this.repaint();

    }

    private JButton createActionButton(Action actionConfig, BusinessEntity businessEntity) {
        JButton actionButton = new JButton(actionConfig.getName());
        actionButton.setToolTipText("Todo - add toolTip to config");
        actionButton.addActionListener(e -> {

            new Thread(() -> {
                try {
                    ActionScriptExecutor engine = new ActionScriptExecutor();

                    Object result = engine.execute(
                            ApplicationContext.getApplicationContext().getConfigPath(),
                            Path.of(actionConfig.getScript()),
                            businessEntity
                    );

                    SwingUtilities.invokeLater(()
                            -> {
                        if (result != null) {
                            JOptionPane.showMessageDialog(null, "Result: " + result);
                        }
                    }
                    );

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }).start();

        });
        return actionButton;
    }
}
