package org.mydevnotes.mst.ui;

import javax.swing.JButton;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntitySelectionListener;
import org.mydevnotes.mst.config.AppConfig;
import org.mydevnotes.mst.config.BusinessEntityConfig;
import org.mydevnotes.mst.dao.BusinessEntity;

/**
 *
 * @author vupma
 */
public class JPanelBusinessEntityActions extends javax.swing.JPanel implements BusinessEntitySelectionListener {

    /**
     * Creates new form JPanelBusinessEntityActions
     */
    public JPanelBusinessEntityActions() {
        initComponents();
        ApplicationContext.getApplicationContext().addSelectionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Test");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onMainBusinessEntitySelected(BusinessEntity businessEntity) {

    }

    @Override
    public void onChildBusinessEntitySelected(BusinessEntity businessEntity) {

        this.removeAll();

        if (businessEntity != null) {

            AppConfig appConfig = ApplicationContext.getApplicationContext().getAppConfig();

            var entityConfig = appConfig.getBusinessEntityConfig().stream().filter(cfg -> cfg.getBusinessEntityType().equals(businessEntity.getType())).findFirst().orElse(null);

            if (entityConfig != null) {
                JButton b1 = new JButton("Start");
                JButton b2 = new JButton("Stop");

                this.add(b1);
                this.add(b2);
            }

        }

        this.revalidate();
        this.repaint();

    }
}
