package org.mydevnotes.mst.ui;

import java.nio.file.Path;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntityListener;
import org.mydevnotes.mst.action.ActionScriptExecutor;
import org.mydevnotes.mst.config.AppConfig;
import org.mydevnotes.mst.dao.BusinessEntity;

/**
 *
 * @author vupma
 */
public class JPanelBusinessEntityActions extends javax.swing.JPanel implements BusinessEntityListener {

    /**
     * Creates new form JPanelBusinessEntityActions
     */
    public JPanelBusinessEntityActions() {
        initComponents();
        ApplicationContext.getApplicationContext().addSelectionListener((BusinessEntityListener) this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Test");
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onBusinessEntitySelected(BusinessEntity businessEntity) {

        this.removeAll();

        if (businessEntity != null) {

            AppConfig appConfig = ApplicationContext.getApplicationContext().getAppConfig();

            var entityConfig = appConfig.getBusinessEntityConfig().stream().filter(cfg -> cfg.getBusinessEntityType().equals(businessEntity.getType())).findFirst().orElse(null);

            if (entityConfig != null) {

                entityConfig.getActions().forEach(actionConfig -> {
                    JButton actionButton = new JButton(actionConfig.getName());
                    actionButton.setToolTipText("Todo - add toolTip to config");
                    actionButton.addActionListener(e -> {

                        new Thread(() -> {
                            try {
                                ActionScriptExecutor engine = new ActionScriptExecutor();

                                Object result = engine.execute(
                                        Path.of(actionConfig.getScript()),
                                        businessEntity
                                );

                                SwingUtilities.invokeLater(()
                                        -> JOptionPane.showMessageDialog(null, "Result: " + result)
                                );

                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }).start();

                    });
                    this.add(actionButton);

                });
            }

        }

        this.revalidate();
        this.repaint();

    }
}
