/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.mydevnotes.mst.ui;

import org.mydevnotes.mst.ui.tree.BusinessEntityNode;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.config.AppConfig;
import org.mydevnotes.mst.config.DataSource;
import org.mydevnotes.mst.config.DetailsObject;
import org.mydevnotes.mst.config.DetailsSection;
import org.mydevnotes.mst.dao.BusinessEntity;
import org.mydevnotes.mst.dao.DBQueryExecutor;
import org.mydevnotes.mst.ui.tree.BusinessEntityTreeCellRenderer;

/**
 *
 * @author vupma
 */
public class JPanelSearchResultDetails extends javax.swing.JPanel implements SearchResultNavigationListener {

    /**
     * Creates new form JPanelDetails
     */
    public JPanelSearchResultDetails() {
        initComponents();
        this.jTreeDetails.setCellRenderer(new BusinessEntityTreeCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDetails = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();

        jScrollPane1.setViewportView(jTreeDetails);

        jSplitPane1.setLeftComponent(jScrollPane1);
        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTreeDetails;
    // End of variables declaration//GEN-END:variables

    @Override
    public void populateDetails(BusinessEntity parentEntity) {

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(new BusinessEntityNode(parentEntity));

        AppConfig config = ApplicationContext.getApplicationContext().getAppConfig();
        var detailsConfig = config.getDetailsSection().stream().filter(cd -> parentEntity.getType().equals(cd.getObjectType())).findFirst().orElse(null);

        if (detailsConfig != null) {
            addDetailsNodes(detailsConfig, root, parentEntity.getId());
        }

        DefaultTreeModel model
                = new DefaultTreeModel(root);

        jTreeDetails.setModel(model);

    }

    private void addDetailsNodes(DetailsSection detailsConfig, DefaultMutableTreeNode root, Object id) {

        for (DetailsObject detailsObjectConfig : detailsConfig.getDetailsObjects()) {

            List<BusinessEntity> detailsEntities = retrieveDetailsEntities(detailsObjectConfig, id);

            if (!detailsEntities.isEmpty()) {

                DefaultMutableTreeNode detailsOfGivenTypeRoot = new DefaultMutableTreeNode(detailsObjectConfig.getObjectType());
                root.add(detailsOfGivenTypeRoot);

                detailsEntities.forEach(entity -> detailsOfGivenTypeRoot.add(new DefaultMutableTreeNode(new BusinessEntityNode(entity))));
            }
        }
    }

    private List<BusinessEntity> retrieveDetailsEntities(DetailsObject detailsObjectConfig, Object id) {
        List<BusinessEntity> detailsEntities = new ArrayList<>();

        DataSource dataSource = ApplicationContext.getApplicationContext().getAppConfig().getDataSources().stream().filter(ds -> detailsObjectConfig.getDataSource().equals(ds.getName())).findFirst().orElse(null);

        if (dataSource != null) {
            if ("db".equals(dataSource.getType()) && "PostgreSQL".equals(dataSource.getConnectionDetails().getType())) {

                HikariDataSource databaseDataStore = ApplicationContext.getApplicationContext().getPosgreSQLDataSource(detailsObjectConfig.getDataSource());

                try (Connection connection = databaseDataStore.getConnection();) {

                    detailsEntities = DBQueryExecutor.execute(detailsObjectConfig, connection, id);
                    ApplicationContext.getApplicationContext().getEventLogger().addLog("Found " + detailsEntities.size() + " " + detailsObjectConfig.getObjectType() + "(s)\n");

                } catch (Exception ex) {
                    ApplicationContext.getApplicationContext().getEventLogger().addLog("Error during details query execution " + ex.getMessage());
                    Logger.getLogger(JPanelSearchOption.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        return detailsEntities;
    }
}
