package org.mydevnotes.mst.ui;

import org.mydevnotes.mst.config.SearchOption;

/**
 *
 * @author vupma
 */
public class JPanelSearchOptionsContainer extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSearchSection
     */
    public JPanelSearchOptionsContainer() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables

    void addSearchOption(SearchOption searchOption, JPanelSearchResultSet resultUi) {
        
        JPanelSearchOption newSearchOptionPanel = new JPanelSearchOption(searchOption, resultUi);
        jTabbedPane.addTab(searchOption.getName(), newSearchOptionPanel);
        
    }
}
