package org.mydevnotes.mst.ui;

import org.mydevnotes.mst.ui.tree.BusinessEntityNode;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntityListener;
import org.mydevnotes.mst.BusinessEntitySelectionListener;
import org.mydevnotes.mst.dao.BusinessEntity;
import org.mydevnotes.mst.ui.tree.BusinessEntityTreeCellRenderer;

/**
 *
 * @author vupma
 */
public class JPanelSearchResultDetails extends javax.swing.JPanel implements BusinessEntityListener {

    private BusinessEntitySelectionListener businessEntitySelectionListener = ApplicationContext.getApplicationContext().getApplicationController();

    /**
     * Creates new form JPanelDetails
     */
    public JPanelSearchResultDetails() {
        initComponents();

        this.jTreeDetails.setRowHeight(16);
        this.jTreeDetails.setCellRenderer(new BusinessEntityTreeCellRenderer());

        this.jPanelSearchResultSetAttributes.setRowHaveDetails(false);

        this.jTreeDetails.addTreeSelectionListener(e -> {

            DefaultMutableTreeNode node
                    = (DefaultMutableTreeNode) this.jTreeDetails.getLastSelectedPathComponent();

            if (node == null) {
                return;
            }

            Object obj = node.getUserObject();

            if (obj instanceof BusinessEntityNode entityNode) {

                System.out.println(entityNode.getBusinessEntity().getId());
                System.out.println(entityNode.getBusinessEntity().getAttributes());

                // trigger your logic here
                if (entityNode.getBusinessEntity() != null) {
                    this.businessEntitySelectionListener.onChildBusinessEntitySelected(entityNode.getBusinessEntity());
                    this.jPanelSearchResultSetAttributes.setBusinessEntity(entityNode.getBusinessEntity());

                    this.refreshSelectionDetails(entityNode.getBusinessEntity());
                }
            } else {
                this.jPanelSearchResultSetAttributes.cleanup();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDetails = new javax.swing.JTree();
        jTabbedPaneSelectionDetails = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelSearchResultSetAttributes = new org.mydevnotes.mst.ui.JPanelSearchResultSet();
        jPanelBusinessEntityActions1 = new org.mydevnotes.mst.ui.JPanelBusinessEntityActions();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTreeDetails);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTabbedPaneSelectionDetails.setToolTipText("");

        jScrollPane2.setViewportView(jPanelSearchResultSetAttributes);

        jTabbedPaneSelectionDetails.addTab("Attributes", null, jScrollPane2, "");

        jSplitPane1.setRightComponent(jTabbedPaneSelectionDetails);
        jTabbedPaneSelectionDetails.getAccessibleContext().setAccessibleName("Attributes");

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
        add(jPanelBusinessEntityActions1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.mydevnotes.mst.ui.JPanelBusinessEntityActions jPanelBusinessEntityActions1;
    private org.mydevnotes.mst.ui.JPanelSearchResultSet jPanelSearchResultSetAttributes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneSelectionDetails;
    private javax.swing.JTree jTreeDetails;
    // End of variables declaration//GEN-END:variables

    public static void expandAll(JTree tree) {
        int row = 0;

        while (row < tree.getRowCount()) {
            tree.expandRow(row);
            row++;
        }
    }

    private void refreshSelectionDetails(BusinessEntity selection) {

        jTabbedPaneSelectionDetails.removeAll();
        if (selection != null) {

            selection.getDetails().forEach((key, value) -> {
                JPanelSearchResultSet jPanelSearchResultSet = new JPanelSearchResultSet();
                jPanelSearchResultSet.setBusinessEntityDetail(selection, key);
                jTabbedPaneSelectionDetails.add(key, jPanelSearchResultSet);
            });
        }
    }

    @Override
    public void onBusinessEntitySelected(BusinessEntity businessEntity) {

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(new BusinessEntityNode(businessEntity));
        this.populateTreeWithBusinessEntityChilds(root, businessEntity);

        DefaultTreeModel model = new DefaultTreeModel(root);

        this.jTreeDetails.setModel(model);
        expandAll(this.jTreeDetails);

    }

    public void populateTreeWithBusinessEntityChilds(DefaultMutableTreeNode root, BusinessEntity businessEntity) {

        businessEntity.getChildrens().forEach((childrenType, childrens) -> {

            DefaultMutableTreeNode detailsOfGivenTypeRoot = new DefaultMutableTreeNode(childrenType);
            root.add(detailsOfGivenTypeRoot);

            childrens.forEach(child -> {
                DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(new BusinessEntityNode(child));
                detailsOfGivenTypeRoot.add(childNode);
                this.populateTreeWithBusinessEntityChilds(childNode, child);
            });

        });

    }
}
