package org.mydevnotes.mst.ui;

import javax.swing.text.DefaultCaret;
import org.mydevnotes.mst.EventLogger;

/**
 *
 * @author vupma
 */
public class JPanelDebugOutput extends javax.swing.JPanel implements EventLogger {

    /**
     * Creates new form JPanelDebugOutput
     */
    public JPanelDebugOutput() {
        initComponents();
        
        DefaultCaret caret = (DefaultCaret) jTextAreaLogs.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLogs = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTextAreaLogs.setColumns(20);
        jTextAreaLogs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLogs);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLogs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addLog(String log) {
        jTextAreaLogs.append(log + System.lineSeparator());
    }
}
