package org.mydevnotes.mst.ui;

import org.mydevnotes.mst.config.DataSource;
import org.mydevnotes.mst.datasource.DataSourceType;

/**
 *
 * @author vupma
 */
public class JPanelConfigContainer extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConfig
     */
    public JPanelConfigContainer() {
        initComponents();        
    }
    
    public void addDataSourceConfig(DataSource dataSource){
        
        DataSourceType dataSourceType= DataSourceType.fromValue(dataSource.getType());
        switch (dataSourceType) {
            case DataSourceType.DB -> jTabbedPane.addTab(dataSource.getName(),new JPanelDBConfig(dataSource));
            // TODO once specific values needed for JMS create new component
            case DataSourceType.JMS -> jTabbedPane.addTab(dataSource.getName(),new JPanelDBConfig(dataSource));
        }        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
