package org.mydevnotes.mst.ui;

import org.mydevnotes.mst.ui.tree.BusinessEntityNode;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.BusinessEntitySelectionListener;
import org.mydevnotes.mst.config.AppConfig;
import org.mydevnotes.mst.config.DataSource;
import org.mydevnotes.mst.config.SearchDetail;
import org.mydevnotes.mst.dao.BusinessEntity;
import org.mydevnotes.mst.dao.DBQueryExecutor;
import org.mydevnotes.mst.ui.tree.BusinessEntityTreeCellRenderer;

/**
 *
 * @author vupma
 */
public class JPanelSearchResultDetails extends javax.swing.JPanel implements SearchResultNavigationListener {

    // safe guard against infinite loops
    private static final int MAX_TREE_HIGHT = 15;
    private BusinessEntitySelectionListener businessEntitySelectionListener = ApplicationContext.getApplicationContext();

    /**
     * Creates new form JPanelDetails
     */
    public JPanelSearchResultDetails() {
        initComponents();
        this.jTreeDetails.setCellRenderer(new BusinessEntityTreeCellRenderer());

        this.jTreeDetails.addTreeSelectionListener(e -> {

            DefaultMutableTreeNode node
                    = (DefaultMutableTreeNode) this.jTreeDetails.getLastSelectedPathComponent();

            if (node == null) {
                return;
            }

            Object obj = node.getUserObject();

            if (obj instanceof BusinessEntityNode entityNode) {

                System.out.println(entityNode.getBusinessEntity().getId());
                System.out.println(entityNode.getBusinessEntity().getAttributes());

                // trigger your logic here
                if (entityNode.getBusinessEntity() != null) {
                    this.businessEntitySelectionListener.setChildBusinessEntity(entityNode.getBusinessEntity());
                    this.jPanelSearchResultSetAttributes.setBusinessEntity(entityNode.getBusinessEntity());
                }
            } else {
                this.jPanelSearchResultSetAttributes.cleanup();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDetails = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelSearchResultSetAttributes = new org.mydevnotes.mst.ui.JPanelSearchResultSet();

        jScrollPane1.setViewportView(jTreeDetails);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setViewportView(jPanelSearchResultSetAttributes);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.mydevnotes.mst.ui.JPanelSearchResultSet jPanelSearchResultSetAttributes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTreeDetails;
    // End of variables declaration//GEN-END:variables

    @Override
    public void populateDetails(BusinessEntity parentEntity) {

        this.businessEntitySelectionListener.setChildBusinessEntity(null);
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(new BusinessEntityNode(parentEntity));

        addDetailsNodes(root, parentEntity, 0);

        DefaultTreeModel model
                = new DefaultTreeModel(root);

        jTreeDetails.setModel(model);
        expandAll(jTreeDetails);
    }

    private void addDetailsNodes(DefaultMutableTreeNode root, BusinessEntity parentEntity, int treeHight) {

        if (treeHight > MAX_TREE_HIGHT) {
            return;
        }

        AppConfig config = ApplicationContext.getApplicationContext().getAppConfig();
        var detailsConfig = config.getChildEntities().stream().filter(cd -> parentEntity.getType().equals(cd.getBusinessEntityType())).findFirst().orElse(null);

        if (detailsConfig != null) {
            for (SearchDetail detailsObjectConfig : detailsConfig.getSearchDetails()) {

                List<BusinessEntity> detailsEntities = retrieveDetailsEntities(detailsObjectConfig, parentEntity.getId());

                if (!detailsEntities.isEmpty()) {

                    DefaultMutableTreeNode detailsOfGivenTypeRoot = new DefaultMutableTreeNode(detailsObjectConfig.getBusinessEntityType());
                    root.add(detailsOfGivenTypeRoot);

                    detailsEntities.forEach(entity -> {
                        detailsOfGivenTypeRoot.add(new DefaultMutableTreeNode(new BusinessEntityNode(entity)));
                        addDetailsNodes(detailsOfGivenTypeRoot, entity, treeHight + 1);
                    });
                }
            }
        }
    }

    private List<BusinessEntity> retrieveDetailsEntities(SearchDetail detailsObjectConfig, Object id) {
        List<BusinessEntity> detailsEntities = new ArrayList<>();

        DataSource dataSource = ApplicationContext.getApplicationContext().getAppConfig().getDataSources().stream().filter(ds -> detailsObjectConfig.getDataSource().equals(ds.getName())).findFirst().orElse(null);

        if (dataSource != null) {
            if ("db".equals(dataSource.getType()) && "PostgreSQL".equals(dataSource.getConnectionDetails().getType())) {

                HikariDataSource databaseDataStore = ApplicationContext.getApplicationContext().getPosgreSQLDataSource(detailsObjectConfig.getDataSource());

                try (Connection connection = databaseDataStore.getConnection();) {

                    detailsEntities = DBQueryExecutor.execute(detailsObjectConfig, connection, id);
                    ApplicationContext.getApplicationContext().getEventLogger().addLog("Found " + detailsEntities.size() + " " + detailsObjectConfig.getBusinessEntityType() + "(s)\n");

                } catch (Exception ex) {
                    ApplicationContext.getApplicationContext().getEventLogger().addLog("Error during details query execution " + ex.getMessage());
                    Logger.getLogger(JPanelSearchOption.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        return detailsEntities;
    }

    public static void expandAll(JTree tree) {
        int row = 0;

        while (row < tree.getRowCount()) {
            tree.expandRow(row);
            row++;
        }
    }
}
