package org.mydevnotes.mst.ui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.mydevnotes.mst.ApplicationContext;
import org.mydevnotes.mst.DataSourceNotFoundException;
import org.mydevnotes.mst.config.SearchOption;
import org.mydevnotes.mst.config.SearchParameter;
import org.mydevnotes.mst.dao.PostgreSqlDataRetriever;

/**
 *
 * @author vupma
 */
public class JPanelSearchOption extends javax.swing.JPanel {

    private SearchOption searchOption;
    private GridBagConstraints gbc;
    private int row = 0;
    private JPanelSearchResultSet resultUi;
    Map<String, String> paramValues = new HashMap<>();

    /**
     * Creates new form JPanelSearchOption
     */
    public JPanelSearchOption() {
        initComponents();
    }

    JPanelSearchOption(SearchOption searchOption, JPanelSearchResultSet resultUi) {
        this();

        this.searchOption = searchOption;
        this.resultUi = resultUi;

        gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        jPanel1.setLayout(new GridBagLayout());

        for (SearchParameter parameter : searchOption.getSearchParameters()) {
            JTextField newField = new JTextField(15);
            newField.setName(parameter.getName());
            bindTextField(newField, this.paramValues);
            addField(parameter.getTitle(), newField);
        }
    }

    private void addField(String labelText, JComponent field) {

        // label
        gbc.gridx = 0;
        gbc.gridy = row;
        gbc.weightx = 0;

        jPanel1.add(new JLabel(labelText), gbc);

        // input
        gbc.gridx = 1;
        gbc.weightx = 1;

        jPanel1.add(field, gbc);

        row++;
    }

    public static void bindTextField(
            JTextField field,
            Map<String, String> values
    ) {

        field.getDocument().addDocumentListener(
                new DocumentListener() {

            private void update() {

                values.put(
                        field.getName(),
                        field.getText()
                );
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                update();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                update();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                update();
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneParameters = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        jScrollPaneParameters.setViewportView(jPanel1);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneParameters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSearch)
                    .addComponent(jScrollPaneParameters))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        try {

            if (ApplicationContext.getApplicationContext().getPosgreSQLDataSource(this.searchOption.getDataSource()) == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Not connected to " + this.searchOption.getDataSource(),
                        "DB connection error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            ApplicationContext.getApplicationContext().getEventLogger().addLog("Execute query " + this.searchOption.getName() + "; for " + this.paramValues + "\n");

            try (Connection connection = ApplicationContext.getApplicationContext().getPosgreSQLDataSource(this.searchOption.getDataSource()).getConnection();) {
                DefaultTableModel tableModel = PostgreSqlDataRetriever.execute(this.searchOption, connection, this.paramValues);

                this.resultUi.setTableModel(tableModel, this.searchOption.getBusinessEntityType());

            } catch (Exception ex) {
                ApplicationContext.getApplicationContext().getEventLogger().addLog("Error during query execution " + ex.getMessage());
                Logger.getLogger(JPanelSearchOption.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (DataSourceNotFoundException ex) {
            System.getLogger(JPanelSearchOption.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                    this,
                    "Connection " + this.searchOption.getDataSource() + "not configured",
                    "DB connection error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_jButtonSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneParameters;
    // End of variables declaration//GEN-END:variables
}
